import { useState } from "react";
import { Platform, SafeAreaView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from "react-native";
import { configureDevice, runBackup, type BackupProgress } from "../src/backup";
import { setAutomaticBackup } from "../src/background";

export default function Home() {
  const [server, setServer] = useState(Platform.OS === "android" ? "http://10.0.2.2:8000" : "http://localhost:8000"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [otp, setOtp] = useState("");
  const [connected, setConnected] = useState(false); const [automatic, setAutomatic] = useState(false); const [progress, setProgress] = useState<BackupProgress | null>(null); const [message, setMessage] = useState("Connect this phone to begin.");
  async function connect() { try { await configureDevice(server, email, password, "My phone", otp || undefined); setConnected(true); setMessage("Connected. Your originals and metadata are ready to back up."); } catch (error) { setMessage(String(error)); } }
  async function backup() { try { setMessage("Backing up…"); const result = await runBackup(setProgress); setMessage(`Complete: ${result.uploaded} uploaded, ${result.skipped} already safe.`); } catch (error) { setMessage(String(error)); } }
  return <SafeAreaView style={styles.safe}><View style={styles.card}><Text style={styles.brand}>Drivebound</Text><Text style={styles.title}>Your camera roll, backed by your own drive.</Text><Text style={styles.copy}>{message}</Text>
    {!connected && <><TextInput style={styles.input} value={server} onChangeText={setServer} autoCapitalize="none" placeholder="Server URL" /><Text style={styles.serverHint}>{Platform.OS === "android" ? "Emulator: 10.0.2.2 · USB device with adb reverse: localhost" : "Use the address of the computer running Drivebound"}</Text><TextInput style={styles.input} value={email} onChangeText={setEmail} autoCapitalize="none" placeholder="Email" /><TextInput style={styles.input} value={password} onChangeText={setPassword} secureTextEntry placeholder="Password" /><TextInput style={styles.input} value={otp} onChangeText={setOtp} keyboardType="number-pad" placeholder="Authenticator code (if enabled)" /><TouchableOpacity style={styles.button} onPress={connect}><Text style={styles.buttonText}>Connect device</Text></TouchableOpacity></>}
    {connected && <><View style={styles.row}><View><Text style={styles.label}>Automatic backup</Text><Text style={styles.hint}>Runs when the operating system allows.</Text></View><Switch value={automatic} onValueChange={async value => { setAutomatic(value); await setAutomaticBackup(value); }} /></View><TouchableOpacity style={styles.button} onPress={backup}><Text style={styles.buttonText}>Back up now</Text></TouchableOpacity>{progress && <Text style={styles.stats}>{progress.scanned} scanned · {progress.uploaded} uploaded · {progress.skipped} safe{"\n"}{progress.current}</Text>}</>}
  </View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:"#e8edf3",justifyContent:"center",padding:20},card:{padding:28,borderRadius:28,backgroundColor:"#e8edf3",shadowColor:"#77889b",shadowOpacity:.35,shadowRadius:18,elevation:8},brand:{color:"#2266d5",fontWeight:"800",fontSize:18},title:{fontSize:32,fontWeight:"800",color:"#172335",marginVertical:14},copy:{color:"#526174",lineHeight:22,marginBottom:18},input:{backgroundColor:"#f5f8fb",padding:16,borderRadius:14,marginBottom:12,color:"#172335"},serverHint:{fontSize:11,color:"#6b7888",lineHeight:16,marginTop:-4,marginBottom:12,paddingHorizontal:4},button:{backgroundColor:"#2266d5",padding:17,borderRadius:15,alignItems:"center",marginTop:8},buttonText:{color:"white",fontWeight:"700"},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingVertical:18},label:{fontWeight:"700",fontSize:17,color:"#172335"},hint:{fontSize:12,color:"#6b7888"},stats:{marginTop:18,color:"#526174",lineHeight:22}});
