"use client";

import Link from "../safe-link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { apiRequest } from "../api-client";
import type { DriveboundUser } from "../auth-gate";

type Session = { id: string; ip_address: string | null; user_agent: string | null; last_seen_at: string; expires_at: string; created_at: string; current: boolean };
type Audit = { id: string; event_type: string; ip_address: string | null; user_agent: string | null; created_at: string };

export function ProfilePage() {
  const [user, setUser] = useState<DriveboundUser | null>(null); const [sessions, setSessions] = useState<Session[]>([]); const [events, setEvents] = useState<Audit[]>([]); const [tab, setTab] = useState("account"); const [message, setMessage] = useState<string | null>(null);
  const [name, setName] = useState(""); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState("");
  const [mfaSecret, setMfaSecret] = useState(""); const [mfaUri, setMfaUri] = useState(""); const [mfaCode, setMfaCode] = useState(""); const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);
  const [mfaPassword, setMfaPassword] = useState(""); const [mfaDisableCode, setMfaDisableCode] = useState("");
  const [deletePassword, setDeletePassword] = useState(""); const [deleteCode, setDeleteCode] = useState(""); const [deleteConfirmation, setDeleteConfirmation] = useState("");

  const load = useCallback(async () => {
    const [me, sessionList, auditList] = await Promise.all([apiRequest("/api/v1/auth/me"), apiRequest("/api/v1/auth/sessions"), apiRequest("/api/v1/auth/audit")]);
    if (!me.ok) { window.location.assign("/auth"); return; }
    const account = await me.json(); setUser(account); setName(account.display_name ?? "");
    if (sessionList.ok) setSessions(await sessionList.json()); if (auditList.ok) setEvents(await auditList.json());
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);

  const jsonAction = async (path: string, body: object, method = "POST") => {
    setMessage(null); const response = await apiRequest(path, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); setMessage(result.message ?? result.detail ?? (response.ok ? "Saved." : "Could not save.")); if (response.ok) await load(); return { response, result };
  };
  const updateProfile = (e: FormEvent) => { e.preventDefault(); void jsonAction("/api/v1/auth/profile", { display_name: name }, "PATCH"); };
  const changePassword = (e: FormEvent) => { e.preventDefault(); void jsonAction("/api/v1/auth/change-password", { current_password: currentPassword, new_password: newPassword }).then(({ response }) => { if (response.ok) { setCurrentPassword(""); setNewPassword(""); } }); };
  const startMfa = async () => { const response = await apiRequest("/api/v1/auth/mfa/setup", { method: "POST" }); const value = await response.json(); if (response.ok) { setMfaSecret(value.secret); setMfaUri(value.provisioning_uri); setMessage("Add the secret to your authenticator, then enter its six-digit code."); } else setMessage(value.detail ?? "Two-factor setup could not be started."); };
  const confirmMfa = async () => { const { response, result } = await jsonAction("/api/v1/auth/mfa/confirm", { code: mfaCode }); if (response.ok) setRecoveryCodes(result.recovery_codes); };
  const disableMfa = async () => { const { response } = await jsonAction("/api/v1/auth/mfa", { password: mfaPassword, code: mfaDisableCode }, "DELETE"); if (response.ok) { setMfaPassword(""); setMfaDisableCode(""); setRecoveryCodes([]); } };
  const exportAccount = async () => { const response = await apiRequest("/api/v1/auth/export"); if (!response.ok) { setMessage("Your account export could not be prepared."); return; } const blob = new Blob([JSON.stringify(await response.json(), null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "drivebound-account-export.json"; link.click(); URL.revokeObjectURL(link.href); setMessage("Account export downloaded."); };
  const deleteAccount = async () => { const { response } = await jsonAction("/api/v1/auth/account", { password: deletePassword, code: deleteCode || undefined, confirmation: deleteConfirmation }, "DELETE"); if (response.ok) window.location.assign("/"); };
  const signOut = async () => { await apiRequest("/api/v1/auth/logout", { method: "POST" }); window.location.assign("/"); };

  if (!user) return <main className="app-loading"><p>Opening your profileâ€¦</p></main>;
  return <main className="profile-shell"><header className="profile-header"><Link className="brand" href="/"><span className="brand-mark">D</span>Drivebound</Link><nav><Link href="/library">Library</Link><button className="secondary-button" onClick={() => void signOut()}>Sign out</button></nav></header><div className="profile-layout"><aside><div className="profile-avatar">{(user.display_name ?? user.email)[0].toUpperCase()}</div><h1>{user.display_name ?? "Drivebound account"}</h1><p>{user.email}</p>{["account", "security", "sessions", "activity", "data"].map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => { setTab(item); setMessage(null); }}>{item}</button>)}</aside><section className="profile-panel">{message && <p className="profile-message" role="status">{message}</p>}
    {tab === "account" && <><span className="eyebrow">Profile</span><h2>Account information</h2><div className="status-card"><span className="drive-light online" /><div><strong>Email verified</strong><small>{new Date(user.email_verified_at!).toLocaleString()}</small></div></div><form className="settings-form" onSubmit={updateProfile}><label>Display name<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>Email address<input value={user.email} disabled /></label><button className="primary-button">Save profile</button></form></>}
    {tab === "security" && <><span className="eyebrow">Security</span><h2>Password and two-factor authentication</h2><form className="settings-form" onSubmit={changePassword}><h3>Change password</h3><label>Current password<input type="password" required value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} /></label><label>New password<input type="password" minLength={12} required value={newPassword} onChange={(e) => setNewPassword(e.target.value)} /></label><button className="primary-button">Change password</button></form><div className="settings-card"><h3>Authenticator app</h3><p>{user.two_factor_enabled ? "Two-factor authentication is protecting this account." : "Add a time-based code from any compatible authenticator app."}</p>{user.two_factor_enabled && <div className="mfa-setup"><label>Password<input type="password" value={mfaPassword} onChange={(e) => setMfaPassword(e.target.value)} /></label><label>Authenticator or recovery code<input value={mfaDisableCode} onChange={(e) => setMfaDisableCode(e.target.value)} /></label><button className="secondary-button" onClick={() => void disableMfa()}>Disable two-factor authentication</button></div>}{!user.two_factor_enabled && !mfaSecret && <button className="secondary-button" onClick={() => void startMfa()}>Set up two-factor authentication</button>}{mfaSecret && <div className="mfa-setup"><label>Setup secret<input readOnly value={mfaSecret} /></label><details><summary>Authenticator URI</summary><code>{mfaUri}</code></details><label>Six-digit code<input inputMode="numeric" value={mfaCode} onChange={(e) => setMfaCode(e.target.value)} /></label><button className="primary-button" onClick={() => void confirmMfa()}>Confirm and enable</button></div>}{recoveryCodes.length > 0 && <div className="recovery-codes"><strong>Save these one-time recovery codes now</strong>{recoveryCodes.map((code) => <code key={code}>{code}</code>)}</div>}</div></>}
    {tab === "sessions" && <><span className="eyebrow">Devices</span><h2>Active sessions</h2><p>Revoke any browser or device you no longer recognize.</p><div className="session-list">{sessions.map((item) => <article key={item.id}><div><strong>{item.current ? "This device" : item.user_agent?.split(" ").slice(0, 3).join(" ") || "Unknown device"}</strong><span>{item.ip_address ?? "Unknown network"} Â· Last active {new Date(item.last_seen_at).toLocaleString()}</span></div>{!item.current && <button onClick={() => void apiRequest(`/api/v1/auth/sessions/${item.id}`, { method: "DELETE" }).then(load)}>Revoke</button>}</article>)}</div></>}
    {tab === "activity" && <><span className="eyebrow">Audit trail</span><h2>Security history</h2><div className="session-list">{events.map((item) => <article key={item.id}><div><strong>{item.event_type.replaceAll("_", " ")}</strong><span>{new Date(item.created_at).toLocaleString()} Â· {item.ip_address ?? "Unknown network"}</span></div></article>)}</div></>}
    {tab === "data" && <><span className="eyebrow">Data control</span><h2>Export or delete your account</h2><div className="settings-card"><h3>Export account manifest</h3><p>Download account information and a list of every asset with its retrieval URL.</p><button className="secondary-button" onClick={() => void exportAccount()}>Download export</button></div><div className="settings-card danger-zone"><h3>Delete account</h3><p>This removes account metadata. Original files remain preserved on owned storage for administrator-assisted recovery.</p><label>Password<input type="password" value={deletePassword} onChange={(e) => setDeletePassword(e.target.value)} /></label>{user.two_factor_enabled && <label>Two-factor code<input value={deleteCode} onChange={(e) => setDeleteCode(e.target.value)} /></label>}<label>Type DELETE MY ACCOUNT<input value={deleteConfirmation} onChange={(e) => setDeleteConfirmation(e.target.value)} /></label><button disabled={deleteConfirmation !== "DELETE MY ACCOUNT"} onClick={() => void deleteAccount()}>Delete my account</button></div></>}
  </section></div></main>;
}
